#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use 5.010001;
use strict;
use warnings;

use IPC::System::Options qw(readpipe);

my $res = readpipe("this-dist", @ARGV);
exit 1 if $?;
$res =~ s/-/::/g;
print $res;
exit 0;

# ABSTRACT: Return name of Perl module associated with the current directory
# PODNAME:

=head1 SYNOPSIS

 % pwd
 /home/budi/perl-Foo-Bar

 % this-mod
 Foo::Bar

Some common usage:

 # read documentation about the current module
 % man `this-mod`

 # open documentation abut the current module on MetaCPAN (but see this-mod-on-metacpan script)
 % firefox metacpan.org/pod/`this-mod`

Some other examples:

 # (Re)install this module using L<cpanminus|App::cpanminus>:
 % cpanm -n --reinstall `this-mod`


=head1 DESCRIPTION

This script is a wrapper to L<this-dist>, converting the result like C<Foo-Bar>
into C<Foo::Bar>.


=head1 SEE ALSO

L<this-dist>

L<this-mod-on-metacpan>
